context.modules = [
    # Discover AirPlay/RAOP receivers (HomePod, Apple TV, etc.) and
    # present them as PipeWire sinks.
    { name = libpipewire-module-raop-discover
        condition = [ { module.raop = !false } ]
    }
]
